Repository CuteReimu/bilibili, pull requests merged in 2024-04, with the labels that each got.

#37 反射优化(#34)
  util.go
  util_test.go
Labels: 新特性

#45 优化Cookies相关函数
  README.md
  client.go
  client_test.go
Labels: 新特性

#46 合集的api似乎有些问题
  video.go
Labels: bug

#50 python2支持
  tools/gen_struct2.py
Labels: 框架
