Repository CuteReimu/bilibili, pull requests merged in 2024-05, with the labels that each got.

#53 降到Go1.19版本
  .github/workflows/gofmt.yml
  .github/workflows/golangci-lint.yml
  README.md
  go.mod
  go.sum
  util_test.go
Labels: 框架

#54 对B站返回的错误码进行处理
  README.md
  util.go
Labels: 新特性, question, 框架

#57 工具生成结果去掉转义符&清空历史记录 接口
  history.go
  tools/gen_struct.py
  tools/gen_struct2.py
Labels: 新特性

#59 浏览器复制的cookies和`GetCookiesString`获取的有所不同
  README.md
  client.go
  client_test.go
Labels: bug, 框架
